// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testp.proto

#include "testp.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR mData_MpEntry_DoNotUse::mData_MpEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct mData_MpEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR mData_MpEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~mData_MpEntry_DoNotUseDefaultTypeInternal() {}
  union {
    mData_MpEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 mData_MpEntry_DoNotUseDefaultTypeInternal _mData_MpEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR mData::mData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.mp_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct mDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR mDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~mDataDefaultTypeInternal() {}
  union {
    mData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 mDataDefaultTypeInternal _mData_default_instance_;
static ::_pb::Metadata file_level_metadata_testp_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_testp_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_testp_2eproto = nullptr;

const uint32_t TableStruct_testp_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::mData_MpEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::mData_MpEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mData_MpEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::mData_MpEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mData, _impl_.mp_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::mData_MpEntry_DoNotUse)},
  { 10, -1, -1, sizeof(::mData)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_mData_MpEntry_DoNotUse_default_instance_._instance,
  &::_mData_default_instance_._instance,
};

const char descriptor_table_protodef_testp_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013testp.proto\"N\n\005mData\022\032\n\002mp\030\001 \003(\0132\016.mDa"
  "ta.MpEntry\032)\n\007MpEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005va"
  "lue\030\002 \001(\005:\0028\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_testp_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_testp_2eproto = {
    false, false, 101, descriptor_table_protodef_testp_2eproto,
    "testp.proto",
    &descriptor_table_testp_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_testp_2eproto::offsets,
    file_level_metadata_testp_2eproto, file_level_enum_descriptors_testp_2eproto,
    file_level_service_descriptors_testp_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_testp_2eproto_getter() {
  return &descriptor_table_testp_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_testp_2eproto(&descriptor_table_testp_2eproto);

// ===================================================================

mData_MpEntry_DoNotUse::mData_MpEntry_DoNotUse() {}
mData_MpEntry_DoNotUse::mData_MpEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void mData_MpEntry_DoNotUse::MergeFrom(const mData_MpEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata mData_MpEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_testp_2eproto_getter, &descriptor_table_testp_2eproto_once,
      file_level_metadata_testp_2eproto[0]);
}

// ===================================================================

class mData::_Internal {
 public:
};

mData::mData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &mData::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:mData)
}
mData::mData(const mData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  mData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.mp_)*/{}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.mp_.MergeFrom(from._impl_.mp_);
  // @@protoc_insertion_point(copy_constructor:mData)
}

inline void mData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.mp_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

mData::~mData() {
  // @@protoc_insertion_point(destructor:mData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void mData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.mp_.Destruct();
  _impl_.mp_.~MapField();
}

void mData::ArenaDtor(void* object) {
  mData* _this = reinterpret_cast< mData* >(object);
  _this->_impl_.mp_.Destruct();
}
void mData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void mData::Clear() {
// @@protoc_insertion_point(message_clear_start:mData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.mp_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* mData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<int32, int32> mp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.mp_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* mData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // map<int32, int32> mp = 1;
  if (!this->_internal_mp().empty()) {
    using MapType = ::_pb::Map<int32_t, int32_t>;
    using WireHelper = mData_MpEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_mp();

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterFlat<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mData)
  return target;
}

size_t mData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<int32, int32> mp = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_mp_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< int32_t, int32_t >::const_iterator
      it = this->_internal_mp().begin();
      it != this->_internal_mp().end(); ++it) {
    total_size += mData_MpEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData mData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    mData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*mData::GetClassData() const { return &_class_data_; }


void mData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<mData*>(&to_msg);
  auto& from = static_cast<const mData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.mp_.MergeFrom(from._impl_.mp_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void mData::CopyFrom(const mData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool mData::IsInitialized() const {
  return true;
}

void mData::InternalSwap(mData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.mp_.InternalSwap(&other->_impl_.mp_);
}

::PROTOBUF_NAMESPACE_ID::Metadata mData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_testp_2eproto_getter, &descriptor_table_testp_2eproto_once,
      file_level_metadata_testp_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mData_MpEntry_DoNotUse*
Arena::CreateMaybeMessage< ::mData_MpEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mData_MpEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::mData*
Arena::CreateMaybeMessage< ::mData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
